apiVersion: v1
kind: Namespace
metadata:
  name: namo-setu
  labels:
    app.kubernetes.io/part-of: namo-setu
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
