replicaCount: 3
image:
  repository: ghcr.io/ankushkumar2811/namo-setu-api
  tag: latest
  pullPolicy: IfNotPresent
service:
  port: 80
resources:
  requests: {cpu: 250m, memory: 384Mi}
  limits: {cpu: "2", memory: 1Gi}
autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 50
  cpuTarget: 65
ingress:
  enabled: true
  className: nginx
  host: api.namosetu.in
config:
  environment: production
  corsOrigins: https://namo-setu.vercel.app
